version: "3"
services:
  docker: 
    container_name: jenkins-docker
    image: docker:dind
    ports:
      - "2376:2376"
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
  jenkins:
    container_name: jenkins-blueocean
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
volumes:
  jenkins-docker-certs:
    external: true
  jenkins-data:
    external: true
networks:
  jenkins:
    external: true
